-- MySQL Script generated by MySQL Workbench
-- Fri Jul 31 01:09:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema filesharing
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `filesharing` ;

-- -----------------------------------------------------
-- Schema filesharing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `filesharing` DEFAULT CHARACTER SET utf8 ;
USE `filesharing` ;

-- -----------------------------------------------------
-- Table `filesharing`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `filesharing`.`user` ;

CREATE TABLE IF NOT EXISTS `filesharing`.`user` (
  `id` INT NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filesharing`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `filesharing`.`files` ;

CREATE TABLE IF NOT EXISTS `filesharing`.`files` (
  `id` VARCHAR(255) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `file_type` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_user_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_files_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `filesharing`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
